name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter  # Ensure Jupyter is installed

      - name: Run Jupyter Notebook tests
        run: |
          python -m jupyter nbconvert --to notebook --execute your_notebook.ipynb --output output_notebook.ipynb

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.